version: '3.4'

services:
  phonebook.service:
    image: ${DOCKER_REGISTRY-}phonebookservice
    build:
      context: .
      dockerfile: Phonebook.Service/Dockerfile

  phonebook.db:
    networks:
      - phonebook_network
    image: "postgres"
    container_name: phonebook.db

  phonebook.data.migration:
    image: ${REGISTRY}/phonebook.data.migration
    networks:
      - phonebook_network
    container_name: phonebook.data.migration
    build:
      context: ..
      target: final
      dockerfile: Phonebook.Data.Migration/Dockerfile
    depends_on:
      - phonebook.db
networks:
  phonebook_network: